package de.vahrson.util;
import java.io.*;
/**
 * This class was generated by a SmartGuide.
 * 
 */
public class AcceptAll implements java.io.FilenameFilter {
/**
 * accept method comment.
 */
public boolean accept(File dir, String name) {
	return true;
}
}