package de.vahrson.pt.om;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;

   
      
   
/**
 * This class was autogenerated by Torque on:
 *
 * [Thu Mar 17 11:26:19 CET 2005]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Parameter
 */
public abstract class BaseParameter extends BaseObject
{
    /** The Peer class */
    private static final ParameterPeer peer =
        new ParameterPeer();

                  
        /**
         * The value for the parameter_id field
         */
        private int parameter_id;
              
        /**
         * The value for the project_id field
         */
        private int project_id;
              
        /**
         * The value for the parameter_key field
         */
        private String parameter_key;
              
        /**
         * The value for the parameter_value field
         */
        private String parameter_value;
      
      
        /**
         * Get the ParameterId
         *
         * @return int
         */
        public int getParameterId()
        {
            return parameter_id;
        }

                                            
        /**
         * Set the value of ParameterId
         *
         * @param v new value
         */
        public void setParameterId(int v) 
        {
          


         if (this.parameter_id != v)
        {
             this.parameter_id = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the ProjectId
         *
         * @return int
         */
        public int getProjectId()
        {
            return project_id;
        }

                                                      
        /**
         * Set the value of ProjectId
         *
         * @param v new value
         */
        public void setProjectId(int v) throws TorqueException
        {
          


         if (this.project_id != v)
        {
             this.project_id = v;
            setModified(true);
        }

                                          
                if (aProject != null && !(aProject.getProjectId()==v))
                {
            aProject = null;
        }
          
                       }


        /**
         * Get the ParameterKey
         *
         * @return String
         */
        public String getParameterKey()
        {
            return parameter_key;
        }

                                                      
        /**
         * Set the value of ParameterKey
         *
         * @param v new value
         */
        public void setParameterKey(String v) throws TorqueException
        {
          


         if (!ObjectUtils.equals(this.parameter_key, v))
        {
             this.parameter_key = v;
            setModified(true);
        }

                                          
                if (aParameterDescription != null && !ObjectUtils.equals(aParameterDescription.getParameterKey(), v))
                {
            aParameterDescription = null;
        }
          
                       }


        /**
         * Get the ParameterValue
         *
         * @return String
         */
        public String getParameterValue()
        {
            return parameter_value;
        }

                                            
        /**
         * Set the value of ParameterValue
         *
         * @param v new value
         */
        public void setParameterValue(String v) 
        {
          


         if (!ObjectUtils.equals(this.parameter_value, v))
        {
             this.parameter_value = v;
            setModified(true);
        }

                  
                       }


 
     
   
             
   
       private ParameterDescription aParameterDescription;

    /**
     * Declares an association between this object and a ParameterDescription object
     *
     * @param v ParameterDescription
     * @throws TorqueException
     */
    public void setParameterDescription(ParameterDescription v) throws TorqueException
    {
           if (v == null)
        {
                         setParameterKey((String)null);
                    }
        else
        {
            setParameterKey(v.getParameterKey());
        }
           aParameterDescription = v;
    }

                 
    /**
     * Get the associated ParameterDescription object
     *
     * @return the associated ParameterDescription object
     * @throws TorqueException
     */
    public ParameterDescription getParameterDescription() throws TorqueException
    {
        if (aParameterDescription == null && (!ObjectUtils.equals(this.parameter_key, null)))
        {
              aParameterDescription = ParameterDescriptionPeer.retrieveByPK(SimpleKey.keyFor(this.parameter_key));
      
            /* The following can be used instead of the line above to
               guarantee the related object contains a reference
               to this object, but this level of coupling
               may be undesirable in many circumstances.
               As it can lead to a db query with many results that may
               never be used.
               ParameterDescription obj = ParameterDescriptionPeer.retrieveByPK(this.parameter_key);
               obj.addParameters(this);
             */
        }
        return aParameterDescription;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey.  e.g.
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setParameterDescriptionKey(ObjectKey key) throws TorqueException
    {
    
                                        setParameterKey(key.toString());
                    }
 
   
             
   
       private Project aProject;

    /**
     * Declares an association between this object and a Project object
     *
     * @param v Project
     * @throws TorqueException
     */
    public void setProject(Project v) throws TorqueException
    {
           if (v == null)
        {
                        setProjectId(0);
                    }
        else
        {
            setProjectId(v.getProjectId());
        }
           aProject = v;
    }

                 
    /**
     * Get the associated Project object
     *
     * @return the associated Project object
     * @throws TorqueException
     */
    public Project getProject() throws TorqueException
    {
        if (aProject == null && (this.project_id > 0))
        {
              aProject = ProjectPeer.retrieveByPK(SimpleKey.keyFor(this.project_id));
      
            /* The following can be used instead of the line above to
               guarantee the related object contains a reference
               to this object, but this level of coupling
               may be undesirable in many circumstances.
               As it can lead to a db query with many results that may
               never be used.
               Project obj = ProjectPeer.retrieveByPK(this.project_id);
               obj.addParameters(this);
             */
        }
        return aProject;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey.  e.g.
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setProjectKey(ObjectKey key) throws TorqueException
    {
    
                                        setProjectId(((NumberKey) key).intValue());
                    }
    
        
    
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
      if (fieldNames == null)
      {
        fieldNames = new ArrayList();
            fieldNames.add("ParameterId");
            fieldNames.add("ProjectId");
            fieldNames.add("ParameterKey");
            fieldNames.add("ParameterValue");
            fieldNames = Collections.unmodifiableList(fieldNames);
      }
      return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
            if (name.equals("ParameterId"))
    {
              return new Integer(getParameterId());
          }
            if (name.equals("ProjectId"))
    {
              return new Integer(getProjectId());
          }
            if (name.equals("ParameterKey"))
    {
              return getParameterKey();
          }
            if (name.equals("ParameterValue"))
    {
              return getParameterValue();
          }
            return null;
    }
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
            if (name.equals(ParameterPeer.PARAMETER_ID))
        {
              return new Integer(getParameterId());
          }
            if (name.equals(ParameterPeer.PROJECT_ID))
        {
              return new Integer(getProjectId());
          }
            if (name.equals(ParameterPeer.PARAMETER_KEY))
        {
              return getParameterKey();
          }
            if (name.equals(ParameterPeer.PARAMETER_VALUE))
        {
              return getParameterValue();
          }
            return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
    {
              return new Integer(getParameterId());
          }
            if (pos == 1)
    {
              return new Integer(getProjectId());
          }
            if (pos == 2)
    {
              return getParameterKey();
          }
            if (pos == 3)
    {
              return getParameterValue();
          }
                return null;
    }

     


    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
             save(ParameterPeer.getMapBuilder()
                .getDatabaseMap().getName());
     }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
         try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }

     }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
      {
        alreadyInSave = true;



  
        // If this object has been modified, then save it to the database.
        if (isModified())
        {
            if (isNew())
            {
                ParameterPeer.doInsert((Parameter) this, con);
                setNew(false);
            }
            else
            {
                ParameterPeer.doUpdate((Parameter) this, con);
            }
        }

              alreadyInSave = false;
      }
      }


                
    
    

        /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  parameter_id ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        
    {
                    setParameterId(((NumberKey) key).intValue());
            }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) 
    {
                    setParameterId(Integer.parseInt(key));
            }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getParameterId());
    }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Parameter copy() throws TorqueException
    {
        return copyInto(new Parameter());
    }

    protected Parameter copyInto(Parameter copyObj) throws TorqueException
    {
        copyObj.setParameterId(parameter_id);
        copyObj.setProjectId(project_id);
        copyObj.setParameterKey(parameter_key);
        copyObj.setParameterValue(parameter_value);

                      copyObj.setParameterId(0);
                        

  
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public ParameterPeer getPeer()
    {
        return peer;
    }
}
