package de.vahrson.pt.om;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;

   
      
   
/**
 * This class was autogenerated by Torque on:
 *
 * [Thu Mar 17 11:26:19 CET 2005]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to PcrProduct
 */
public abstract class BasePcrProduct extends BaseObject
{
    /** The Peer class */
    private static final PcrProductPeer peer =
        new PcrProductPeer();

                  
        /**
         * The value for the pcr_product_id field
         */
        private int pcr_product_id;
              
        /**
         * The value for the left_hit_id field
         */
        private int left_hit_id;
              
        /**
         * The value for the right_hit_id field
         */
        private int right_hit_id;
              
        /**
         * The value for the sequence field
         */
        private String sequence;
              
        /**
         * The value for the seqlen field
         */
        private int seqlen;
              
        /**
         * The value for the tm field
         */
        private double tm;
              
        /**
         * The value for the gc field
         */
        private double gc;
              
        /**
         * The value for the status field
         */
        private int status;
              
        /**
         * The value for the creator field
         */
        private String creator;
      
      
        /**
         * Get the PcrProductId
         *
         * @return int
         */
        public int getPcrProductId()
        {
            return pcr_product_id;
        }

                                                                              
        /**
         * Set the value of PcrProductId
         *
         * @param v new value
         */
        public void setPcrProductId(int v) throws TorqueException
        {
          


         if (this.pcr_product_id != v)
        {
             this.pcr_product_id = v;
            setModified(true);
        }

                  
                                                  
              // update associated ProjectPcrProduct
              if (collProjectPcrProducts != null)
              {
                  for (int i = 0; i < collProjectPcrProducts.size(); i++)
                  {
                      ((ProjectPcrProduct) collProjectPcrProducts.get(i))
                          .setPcrProductId(v);
                  }
              }
                                   }


        /**
         * Get the LeftHitId
         *
         * @return int
         */
        public int getLeftHitId()
        {
            return left_hit_id;
        }

                                                      
        /**
         * Set the value of LeftHitId
         *
         * @param v new value
         */
        public void setLeftHitId(int v) throws TorqueException
        {
          


         if (this.left_hit_id != v)
        {
             this.left_hit_id = v;
            setModified(true);
        }

                                                                                                                
                if (aHitRelatedByLeftHitId != null && !(aHitRelatedByLeftHitId.getHitId()==v))
                {
            aHitRelatedByLeftHitId = null;
        }
          
                       }


        /**
         * Get the RightHitId
         *
         * @return int
         */
        public int getRightHitId()
        {
            return right_hit_id;
        }

                                                      
        /**
         * Set the value of RightHitId
         *
         * @param v new value
         */
        public void setRightHitId(int v) throws TorqueException
        {
          


         if (this.right_hit_id != v)
        {
             this.right_hit_id = v;
            setModified(true);
        }

                                                                                                                
                if (aHitRelatedByRightHitId != null && !(aHitRelatedByRightHitId.getHitId()==v))
                {
            aHitRelatedByRightHitId = null;
        }
          
                       }


        /**
         * Get the Sequence
         *
         * @return String
         */
        public String getSequence()
        {
            return sequence;
        }

                                            
        /**
         * Set the value of Sequence
         *
         * @param v new value
         */
        public void setSequence(String v) 
        {
          


         if (!ObjectUtils.equals(this.sequence, v))
        {
             this.sequence = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Seqlen
         *
         * @return int
         */
        public int getSeqlen()
        {
            return seqlen;
        }

                                            
        /**
         * Set the value of Seqlen
         *
         * @param v new value
         */
        public void setSeqlen(int v) 
        {
          


         if (this.seqlen != v)
        {
             this.seqlen = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Tm
         *
         * @return double
         */
        public double getTm()
        {
            return tm;
        }

                                            
        /**
         * Set the value of Tm
         *
         * @param v new value
         */
        public void setTm(double v) 
        {
          


         if (this.tm != v)
        {
             this.tm = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Gc
         *
         * @return double
         */
        public double getGc()
        {
            return gc;
        }

                                            
        /**
         * Set the value of Gc
         *
         * @param v new value
         */
        public void setGc(double v) 
        {
          


         if (this.gc != v)
        {
             this.gc = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Status
         *
         * @return int
         */
        public int getStatus()
        {
            return status;
        }

                                            
        /**
         * Set the value of Status
         *
         * @param v new value
         */
        public void setStatus(int v) 
        {
          


         if (this.status != v)
        {
             this.status = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Creator
         *
         * @return String
         */
        public String getCreator()
        {
            return creator;
        }

                                            
        /**
         * Set the value of Creator
         *
         * @param v new value
         */
        public void setCreator(String v) 
        {
          


         if (!ObjectUtils.equals(this.creator, v))
        {
             this.creator = v;
            setModified(true);
        }

                  
                       }


 
     
   
                 
      
       private Hit aHitRelatedByLeftHitId;

    /**
     * Declares an association between this object and a Hit object
     *
     * @param v Hit
     * @throws TorqueException
     */
    public void setHitRelatedByLeftHitId(Hit v) throws TorqueException
    {
           if (v == null)
        {
                        setLeftHitId(0);
                    }
        else
        {
            setLeftHitId(v.getHitId());
        }
           aHitRelatedByLeftHitId = v;
    }

                 
    /**
     * Get the associated Hit object
     *
     * @return the associated Hit object
     * @throws TorqueException
     */
    public Hit getHitRelatedByLeftHitId() throws TorqueException
    {
        if (aHitRelatedByLeftHitId == null && (this.left_hit_id > 0))
        {
              aHitRelatedByLeftHitId = HitPeer.retrieveByPK(SimpleKey.keyFor(this.left_hit_id));
      
            /* The following can be used instead of the line above to
               guarantee the related object contains a reference
               to this object, but this level of coupling
               may be undesirable in many circumstances.
               As it can lead to a db query with many results that may
               never be used.
               Hit obj = HitPeer.retrieveByPK(this.left_hit_id);
               obj.addPcrProductsRelatedByLeftHitId(this);
             */
        }
        return aHitRelatedByLeftHitId;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey.  e.g.
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setHitRelatedByLeftHitIdKey(ObjectKey key) throws TorqueException
    {
    
                                        setLeftHitId(((NumberKey) key).intValue());
                    }
 
   
                 
      
       private Hit aHitRelatedByRightHitId;

    /**
     * Declares an association between this object and a Hit object
     *
     * @param v Hit
     * @throws TorqueException
     */
    public void setHitRelatedByRightHitId(Hit v) throws TorqueException
    {
           if (v == null)
        {
                        setRightHitId(0);
                    }
        else
        {
            setRightHitId(v.getHitId());
        }
           aHitRelatedByRightHitId = v;
    }

                 
    /**
     * Get the associated Hit object
     *
     * @return the associated Hit object
     * @throws TorqueException
     */
    public Hit getHitRelatedByRightHitId() throws TorqueException
    {
        if (aHitRelatedByRightHitId == null && (this.right_hit_id > 0))
        {
              aHitRelatedByRightHitId = HitPeer.retrieveByPK(SimpleKey.keyFor(this.right_hit_id));
      
            /* The following can be used instead of the line above to
               guarantee the related object contains a reference
               to this object, but this level of coupling
               may be undesirable in many circumstances.
               As it can lead to a db query with many results that may
               never be used.
               Hit obj = HitPeer.retrieveByPK(this.right_hit_id);
               obj.addPcrProductsRelatedByRightHitId(this);
             */
        }
        return aHitRelatedByRightHitId;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey.  e.g.
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setHitRelatedByRightHitIdKey(ObjectKey key) throws TorqueException
    {
    
                                        setRightHitId(((NumberKey) key).intValue());
                    }
    
                
      
    /**
     * Collection to store aggregation of collProjectPcrProducts
     */
    protected List collProjectPcrProducts;

    /**
     * Temporary storage of collProjectPcrProducts to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initProjectPcrProducts()
    {
        if (collProjectPcrProducts == null)
        {
            collProjectPcrProducts = new ArrayList();
        }
    }

    /**
     * Method called to associate a ProjectPcrProduct object to this object
     * through the ProjectPcrProduct foreign key attribute
     *
     * @param l ProjectPcrProduct
     * @throws TorqueException
     */
    public void addProjectPcrProduct(ProjectPcrProduct l) throws TorqueException
    {
        getProjectPcrProducts().add(l);
        l.setPcrProduct((PcrProduct) this);
    }

    /**
     * The criteria used to select the current contents of collProjectPcrProducts
     */
    private Criteria lastProjectPcrProductsCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getProjectPcrProducts(new Criteria())
     *
     * @throws TorqueException
     */
    public List getProjectPcrProducts() throws TorqueException
    {
        if (collProjectPcrProducts == null)
        {
            collProjectPcrProducts = getProjectPcrProducts(new Criteria(10));
        }
        return collProjectPcrProducts;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this PcrProduct has previously
     * been saved, it will retrieve related ProjectPcrProducts from storage.
     * If this PcrProduct is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getProjectPcrProducts(Criteria criteria) throws TorqueException
    {
        if (collProjectPcrProducts == null)
        {
            if (isNew())
            {
               collProjectPcrProducts = new ArrayList();
            }
            else
            {
                   criteria.add(ProjectPcrProductPeer.PCR_PRODUCT_ID, getPcrProductId() );
                   collProjectPcrProducts = ProjectPcrProductPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                   criteria.add(ProjectPcrProductPeer.PCR_PRODUCT_ID, getPcrProductId());
                   if (!lastProjectPcrProductsCriteria.equals(criteria))
                {
                    collProjectPcrProducts = ProjectPcrProductPeer.doSelect(criteria);
                }
            }
        }
        lastProjectPcrProductsCriteria = criteria;

        return collProjectPcrProducts;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getProjectPcrProducts(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getProjectPcrProducts(Connection con) throws TorqueException
    {
        if (collProjectPcrProducts == null)
        {
            collProjectPcrProducts = getProjectPcrProducts(new Criteria(10), con);
        }
        return collProjectPcrProducts;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this PcrProduct has previously
     * been saved, it will retrieve related ProjectPcrProducts from storage.
     * If this PcrProduct is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getProjectPcrProducts(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collProjectPcrProducts == null)
        {
            if (isNew())
            {
               collProjectPcrProducts = new ArrayList();
            }
            else
            {
                     criteria.add(ProjectPcrProductPeer.PCR_PRODUCT_ID, getPcrProductId());
                     collProjectPcrProducts = ProjectPcrProductPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                     criteria.add(ProjectPcrProductPeer.PCR_PRODUCT_ID, getPcrProductId());
                     if (!lastProjectPcrProductsCriteria.equals(criteria))
                 {
                     collProjectPcrProducts = ProjectPcrProductPeer.doSelect(criteria, con);
                 }
             }
         }
         lastProjectPcrProductsCriteria = criteria;

         return collProjectPcrProducts;
     }

    

     
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this PcrProduct is new, it will return
     * an empty collection; or if this PcrProduct has previously
     * been saved, it will retrieve related ProjectPcrProducts from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in PcrProduct.
     */
    protected List getProjectPcrProductsJoinProject(Criteria criteria)
        throws TorqueException
    {
        if (collProjectPcrProducts == null)
        {
            if (isNew())
            {
               collProjectPcrProducts = new ArrayList();
            }
            else
            {
                   criteria.add(ProjectPcrProductPeer.PCR_PRODUCT_ID, getPcrProductId());
                   collProjectPcrProducts = ProjectPcrProductPeer.doSelectJoinProject(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(ProjectPcrProductPeer.PCR_PRODUCT_ID, getPcrProductId());
               if (!lastProjectPcrProductsCriteria.equals(criteria))
            {
                collProjectPcrProducts = ProjectPcrProductPeer.doSelectJoinProject(criteria);
            }
        }
        lastProjectPcrProductsCriteria = criteria;

        return collProjectPcrProducts;
    }
   
      
         
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this PcrProduct is new, it will return
     * an empty collection; or if this PcrProduct has previously
     * been saved, it will retrieve related ProjectPcrProducts from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in PcrProduct.
     */
    protected List getProjectPcrProductsJoinPcrProduct(Criteria criteria)
        throws TorqueException
    {
        if (collProjectPcrProducts == null)
        {
            if (isNew())
            {
               collProjectPcrProducts = new ArrayList();
            }
            else
            {
                   criteria.add(ProjectPcrProductPeer.PCR_PRODUCT_ID, getPcrProductId());
                   collProjectPcrProducts = ProjectPcrProductPeer.doSelectJoinPcrProduct(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(ProjectPcrProductPeer.PCR_PRODUCT_ID, getPcrProductId());
               if (!lastProjectPcrProductsCriteria.equals(criteria))
            {
                collProjectPcrProducts = ProjectPcrProductPeer.doSelectJoinPcrProduct(criteria);
            }
        }
        lastProjectPcrProductsCriteria = criteria;

        return collProjectPcrProducts;
    }
     



     
    
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
      if (fieldNames == null)
      {
        fieldNames = new ArrayList();
            fieldNames.add("PcrProductId");
            fieldNames.add("LeftHitId");
            fieldNames.add("RightHitId");
            fieldNames.add("Sequence");
            fieldNames.add("Seqlen");
            fieldNames.add("Tm");
            fieldNames.add("Gc");
            fieldNames.add("Status");
            fieldNames.add("Creator");
            fieldNames = Collections.unmodifiableList(fieldNames);
      }
      return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
            if (name.equals("PcrProductId"))
    {
              return new Integer(getPcrProductId());
          }
            if (name.equals("LeftHitId"))
    {
              return new Integer(getLeftHitId());
          }
            if (name.equals("RightHitId"))
    {
              return new Integer(getRightHitId());
          }
            if (name.equals("Sequence"))
    {
              return getSequence();
          }
            if (name.equals("Seqlen"))
    {
              return new Integer(getSeqlen());
          }
            if (name.equals("Tm"))
    {
              return new Double(getTm());
          }
            if (name.equals("Gc"))
    {
              return new Double(getGc());
          }
            if (name.equals("Status"))
    {
              return new Integer(getStatus());
          }
            if (name.equals("Creator"))
    {
              return getCreator();
          }
            return null;
    }
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
            if (name.equals(PcrProductPeer.PCR_PRODUCT_ID))
        {
              return new Integer(getPcrProductId());
          }
            if (name.equals(PcrProductPeer.LEFT_HIT_ID))
        {
              return new Integer(getLeftHitId());
          }
            if (name.equals(PcrProductPeer.RIGHT_HIT_ID))
        {
              return new Integer(getRightHitId());
          }
            if (name.equals(PcrProductPeer.SEQUENCE))
        {
              return getSequence();
          }
            if (name.equals(PcrProductPeer.SEQLEN))
        {
              return new Integer(getSeqlen());
          }
            if (name.equals(PcrProductPeer.TM))
        {
              return new Double(getTm());
          }
            if (name.equals(PcrProductPeer.GC))
        {
              return new Double(getGc());
          }
            if (name.equals(PcrProductPeer.STATUS))
        {
              return new Integer(getStatus());
          }
            if (name.equals(PcrProductPeer.CREATOR))
        {
              return getCreator();
          }
            return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
    {
              return new Integer(getPcrProductId());
          }
            if (pos == 1)
    {
              return new Integer(getLeftHitId());
          }
            if (pos == 2)
    {
              return new Integer(getRightHitId());
          }
            if (pos == 3)
    {
              return getSequence();
          }
            if (pos == 4)
    {
              return new Integer(getSeqlen());
          }
            if (pos == 5)
    {
              return new Double(getTm());
          }
            if (pos == 6)
    {
              return new Double(getGc());
          }
            if (pos == 7)
    {
              return new Integer(getStatus());
          }
            if (pos == 8)
    {
              return getCreator();
          }
                return null;
    }

     


    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
             save(PcrProductPeer.getMapBuilder()
                .getDatabaseMap().getName());
     }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
         try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }

     }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
      {
        alreadyInSave = true;



  
        // If this object has been modified, then save it to the database.
        if (isModified())
        {
            if (isNew())
            {
                PcrProductPeer.doInsert((PcrProduct) this, con);
                setNew(false);
            }
            else
            {
                PcrProductPeer.doUpdate((PcrProduct) this, con);
            }
        }

                                    
                
          if (collProjectPcrProducts != null)
          {
              for (int i = 0; i < collProjectPcrProducts.size(); i++)
              {
                  ((ProjectPcrProduct) collProjectPcrProducts.get(i)).save(con);
              }
          }
                  alreadyInSave = false;
      }
      }


                        
    
    

        /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  pcr_product_id ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
                    setPcrProductId(((NumberKey) key).intValue());
            }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
                    setPcrProductId(Integer.parseInt(key));
            }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getPcrProductId());
    }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public PcrProduct copy() throws TorqueException
    {
        return copyInto(new PcrProduct());
    }

    protected PcrProduct copyInto(PcrProduct copyObj) throws TorqueException
    {
        copyObj.setPcrProductId(pcr_product_id);
        copyObj.setLeftHitId(left_hit_id);
        copyObj.setRightHitId(right_hit_id);
        copyObj.setSequence(sequence);
        copyObj.setSeqlen(seqlen);
        copyObj.setTm(tm);
        copyObj.setGc(gc);
        copyObj.setStatus(status);
        copyObj.setCreator(creator);

                      copyObj.setPcrProductId(0);
                                            

                                  
                
        List v = getProjectPcrProducts();
        for (int i = 0; i < v.size(); i++)
        {
            ProjectPcrProduct obj = (ProjectPcrProduct) v.get(i);
            copyObj.addProjectPcrProduct(obj.copy());
        }
              
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public PcrProductPeer getPeer()
    {
        return peer;
    }
}
