package de.vahrson.pt.om;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;


/**
 * This class was autogenerated by Torque on:
 *
 * [Thu Mar 17 11:26:19 CET 2005]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Orf
 */
public abstract class BaseOrf extends BaseObject
{
    /** The Peer class */
    private static final OrfPeer peer =
        new OrfPeer();

                  
        /**
         * The value for the orf_id field
         */
        private int orf_id;
              
        /**
         * The value for the name field
         */
        private String name;
              
        /**
         * The value for the usa field
         */
        private String usa;
              
        /**
         * The value for the source_usa field
         */
        private String source_usa;
              
        /**
         * The value for the location field
         */
        private String location;
              
        /**
         * The value for the length field
         */
        private int length;
      
      
        /**
         * Get the OrfId
         *
         * @return int
         */
        public int getOrfId()
        {
            return orf_id;
        }

                                                                              
        /**
         * Set the value of OrfId
         *
         * @param v new value
         */
        public void setOrfId(int v) throws TorqueException
        {
          


         if (this.orf_id != v)
        {
             this.orf_id = v;
            setModified(true);
        }

                  
                                                  
              // update associated ProjectOrf
              if (collProjectOrfs != null)
              {
                  for (int i = 0; i < collProjectOrfs.size(); i++)
                  {
                      ((ProjectOrf) collProjectOrfs.get(i))
                          .setOrfId(v);
                  }
              }
                                   }


        /**
         * Get the Name
         *
         * @return String
         */
        public String getName()
        {
            return name;
        }

                                            
        /**
         * Set the value of Name
         *
         * @param v new value
         */
        public void setName(String v) 
        {
          


         if (!ObjectUtils.equals(this.name, v))
        {
             this.name = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Usa
         *
         * @return String
         */
        public String getUsa()
        {
            return usa;
        }

                                            
        /**
         * Set the value of Usa
         *
         * @param v new value
         */
        public void setUsa(String v) 
        {
          


         if (!ObjectUtils.equals(this.usa, v))
        {
             this.usa = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the SourceUsa
         *
         * @return String
         */
        public String getSourceUsa()
        {
            return source_usa;
        }

                                            
        /**
         * Set the value of SourceUsa
         *
         * @param v new value
         */
        public void setSourceUsa(String v) 
        {
          


         if (!ObjectUtils.equals(this.source_usa, v))
        {
             this.source_usa = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Location
         *
         * @return String
         */
        public String getLocation()
        {
            return location;
        }

                                            
        /**
         * Set the value of Location
         *
         * @param v new value
         */
        public void setLocation(String v) 
        {
          


         if (!ObjectUtils.equals(this.location, v))
        {
             this.location = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Length
         *
         * @return int
         */
        public int getLength()
        {
            return length;
        }

                                            
        /**
         * Set the value of Length
         *
         * @param v new value
         */
        public void setLength(int v) 
        {
          


         if (this.length != v)
        {
             this.length = v;
            setModified(true);
        }

                  
                       }


 
        
                
      
    /**
     * Collection to store aggregation of collProjectOrfs
     */
    protected List collProjectOrfs;

    /**
     * Temporary storage of collProjectOrfs to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initProjectOrfs()
    {
        if (collProjectOrfs == null)
        {
            collProjectOrfs = new ArrayList();
        }
    }

    /**
     * Method called to associate a ProjectOrf object to this object
     * through the ProjectOrf foreign key attribute
     *
     * @param l ProjectOrf
     * @throws TorqueException
     */
    public void addProjectOrf(ProjectOrf l) throws TorqueException
    {
        getProjectOrfs().add(l);
        l.setOrf((Orf) this);
    }

    /**
     * The criteria used to select the current contents of collProjectOrfs
     */
    private Criteria lastProjectOrfsCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getProjectOrfs(new Criteria())
     *
     * @throws TorqueException
     */
    public List getProjectOrfs() throws TorqueException
    {
        if (collProjectOrfs == null)
        {
            collProjectOrfs = getProjectOrfs(new Criteria(10));
        }
        return collProjectOrfs;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Orf has previously
     * been saved, it will retrieve related ProjectOrfs from storage.
     * If this Orf is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getProjectOrfs(Criteria criteria) throws TorqueException
    {
        if (collProjectOrfs == null)
        {
            if (isNew())
            {
               collProjectOrfs = new ArrayList();
            }
            else
            {
                   criteria.add(ProjectOrfPeer.ORF_ID, getOrfId() );
                   collProjectOrfs = ProjectOrfPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                   criteria.add(ProjectOrfPeer.ORF_ID, getOrfId());
                   if (!lastProjectOrfsCriteria.equals(criteria))
                {
                    collProjectOrfs = ProjectOrfPeer.doSelect(criteria);
                }
            }
        }
        lastProjectOrfsCriteria = criteria;

        return collProjectOrfs;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getProjectOrfs(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getProjectOrfs(Connection con) throws TorqueException
    {
        if (collProjectOrfs == null)
        {
            collProjectOrfs = getProjectOrfs(new Criteria(10), con);
        }
        return collProjectOrfs;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Orf has previously
     * been saved, it will retrieve related ProjectOrfs from storage.
     * If this Orf is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getProjectOrfs(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collProjectOrfs == null)
        {
            if (isNew())
            {
               collProjectOrfs = new ArrayList();
            }
            else
            {
                     criteria.add(ProjectOrfPeer.ORF_ID, getOrfId());
                     collProjectOrfs = ProjectOrfPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                     criteria.add(ProjectOrfPeer.ORF_ID, getOrfId());
                     if (!lastProjectOrfsCriteria.equals(criteria))
                 {
                     collProjectOrfs = ProjectOrfPeer.doSelect(criteria, con);
                 }
             }
         }
         lastProjectOrfsCriteria = criteria;

         return collProjectOrfs;
     }

    

     
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Orf is new, it will return
     * an empty collection; or if this Orf has previously
     * been saved, it will retrieve related ProjectOrfs from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Orf.
     */
    protected List getProjectOrfsJoinProject(Criteria criteria)
        throws TorqueException
    {
        if (collProjectOrfs == null)
        {
            if (isNew())
            {
               collProjectOrfs = new ArrayList();
            }
            else
            {
                   criteria.add(ProjectOrfPeer.ORF_ID, getOrfId());
                   collProjectOrfs = ProjectOrfPeer.doSelectJoinProject(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(ProjectOrfPeer.ORF_ID, getOrfId());
               if (!lastProjectOrfsCriteria.equals(criteria))
            {
                collProjectOrfs = ProjectOrfPeer.doSelectJoinProject(criteria);
            }
        }
        lastProjectOrfsCriteria = criteria;

        return collProjectOrfs;
    }
   
      
         
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Orf is new, it will return
     * an empty collection; or if this Orf has previously
     * been saved, it will retrieve related ProjectOrfs from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Orf.
     */
    protected List getProjectOrfsJoinOrf(Criteria criteria)
        throws TorqueException
    {
        if (collProjectOrfs == null)
        {
            if (isNew())
            {
               collProjectOrfs = new ArrayList();
            }
            else
            {
                   criteria.add(ProjectOrfPeer.ORF_ID, getOrfId());
                   collProjectOrfs = ProjectOrfPeer.doSelectJoinOrf(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(ProjectOrfPeer.ORF_ID, getOrfId());
               if (!lastProjectOrfsCriteria.equals(criteria))
            {
                collProjectOrfs = ProjectOrfPeer.doSelectJoinOrf(criteria);
            }
        }
        lastProjectOrfsCriteria = criteria;

        return collProjectOrfs;
    }
     



     
    
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
      if (fieldNames == null)
      {
        fieldNames = new ArrayList();
            fieldNames.add("OrfId");
            fieldNames.add("Name");
            fieldNames.add("Usa");
            fieldNames.add("SourceUsa");
            fieldNames.add("Location");
            fieldNames.add("Length");
            fieldNames = Collections.unmodifiableList(fieldNames);
      }
      return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
            if (name.equals("OrfId"))
    {
              return new Integer(getOrfId());
          }
            if (name.equals("Name"))
    {
              return getName();
          }
            if (name.equals("Usa"))
    {
              return getUsa();
          }
            if (name.equals("SourceUsa"))
    {
              return getSourceUsa();
          }
            if (name.equals("Location"))
    {
              return getLocation();
          }
            if (name.equals("Length"))
    {
              return new Integer(getLength());
          }
            return null;
    }
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
            if (name.equals(OrfPeer.ORF_ID))
        {
              return new Integer(getOrfId());
          }
            if (name.equals(OrfPeer.NAME))
        {
              return getName();
          }
            if (name.equals(OrfPeer.USA))
        {
              return getUsa();
          }
            if (name.equals(OrfPeer.SOURCE_USA))
        {
              return getSourceUsa();
          }
            if (name.equals(OrfPeer.LOCATION))
        {
              return getLocation();
          }
            if (name.equals(OrfPeer.LENGTH))
        {
              return new Integer(getLength());
          }
            return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
    {
              return new Integer(getOrfId());
          }
            if (pos == 1)
    {
              return getName();
          }
            if (pos == 2)
    {
              return getUsa();
          }
            if (pos == 3)
    {
              return getSourceUsa();
          }
            if (pos == 4)
    {
              return getLocation();
          }
            if (pos == 5)
    {
              return new Integer(getLength());
          }
                return null;
    }

     


    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
             save(OrfPeer.getMapBuilder()
                .getDatabaseMap().getName());
     }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
         try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }

     }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
      {
        alreadyInSave = true;



  
        // If this object has been modified, then save it to the database.
        if (isModified())
        {
            if (isNew())
            {
                OrfPeer.doInsert((Orf) this, con);
                setNew(false);
            }
            else
            {
                OrfPeer.doUpdate((Orf) this, con);
            }
        }

                                    
                
          if (collProjectOrfs != null)
          {
              for (int i = 0; i < collProjectOrfs.size(); i++)
              {
                  ((ProjectOrf) collProjectOrfs.get(i)).save(con);
              }
          }
                  alreadyInSave = false;
      }
      }


                        
    
    

        /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  orf_id ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
                    setOrfId(((NumberKey) key).intValue());
            }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
                    setOrfId(Integer.parseInt(key));
            }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getOrfId());
    }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Orf copy() throws TorqueException
    {
        return copyInto(new Orf());
    }

    protected Orf copyInto(Orf copyObj) throws TorqueException
    {
        copyObj.setOrfId(orf_id);
        copyObj.setName(name);
        copyObj.setUsa(usa);
        copyObj.setSourceUsa(source_usa);
        copyObj.setLocation(location);
        copyObj.setLength(length);

                      copyObj.setOrfId(0);
                                

                                  
                
        List v = getProjectOrfs();
        for (int i = 0; i < v.size(); i++)
        {
            ProjectOrf obj = (ProjectOrf) v.get(i);
            copyObj.addProjectOrf(obj.copy());
        }
              
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public OrfPeer getPeer()
    {
        return peer;
    }
}
