package de.vahrson.pt.om;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;


/**
 * This class was autogenerated by Torque on:
 *
 * [Thu Mar 17 11:26:19 CET 2005]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to ParameterDescription
 */
public abstract class BaseParameterDescription extends BaseObject
{
    /** The Peer class */
    private static final ParameterDescriptionPeer peer =
        new ParameterDescriptionPeer();

                  
        /**
         * The value for the parameter_key field
         */
        private String parameter_key;
              
        /**
         * The value for the allowed_values field
         */
        private String allowed_values;
              
        /**
         * The value for the default_value field
         */
        private String default_value;
              
        /**
         * The value for the description field
         */
        private String description;
      
      
        /**
         * Get the ParameterKey
         *
         * @return String
         */
        public String getParameterKey()
        {
            return parameter_key;
        }

                                                                              
        /**
         * Set the value of ParameterKey
         *
         * @param v new value
         */
        public void setParameterKey(String v) throws TorqueException
        {
          


         if (!ObjectUtils.equals(this.parameter_key, v))
        {
             this.parameter_key = v;
            setModified(true);
        }

                  
                                                  
              // update associated Parameter
              if (collParameters != null)
              {
                  for (int i = 0; i < collParameters.size(); i++)
                  {
                      ((Parameter) collParameters.get(i))
                          .setParameterKey(v);
                  }
              }
                                   }


        /**
         * Get the AllowedValues
         *
         * @return String
         */
        public String getAllowedValues()
        {
            return allowed_values;
        }

                                            
        /**
         * Set the value of AllowedValues
         *
         * @param v new value
         */
        public void setAllowedValues(String v) 
        {
          


         if (!ObjectUtils.equals(this.allowed_values, v))
        {
             this.allowed_values = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the DefaultValue
         *
         * @return String
         */
        public String getDefaultValue()
        {
            return default_value;
        }

                                            
        /**
         * Set the value of DefaultValue
         *
         * @param v new value
         */
        public void setDefaultValue(String v) 
        {
          


         if (!ObjectUtils.equals(this.default_value, v))
        {
             this.default_value = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Description
         *
         * @return String
         */
        public String getDescription()
        {
            return description;
        }

                                            
        /**
         * Set the value of Description
         *
         * @param v new value
         */
        public void setDescription(String v) 
        {
          


         if (!ObjectUtils.equals(this.description, v))
        {
             this.description = v;
            setModified(true);
        }

                  
                       }


 
        
                
      
    /**
     * Collection to store aggregation of collParameters
     */
    protected List collParameters;

    /**
     * Temporary storage of collParameters to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initParameters()
    {
        if (collParameters == null)
        {
            collParameters = new ArrayList();
        }
    }

    /**
     * Method called to associate a Parameter object to this object
     * through the Parameter foreign key attribute
     *
     * @param l Parameter
     * @throws TorqueException
     */
    public void addParameter(Parameter l) throws TorqueException
    {
        getParameters().add(l);
        l.setParameterDescription((ParameterDescription) this);
    }

    /**
     * The criteria used to select the current contents of collParameters
     */
    private Criteria lastParametersCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getParameters(new Criteria())
     *
     * @throws TorqueException
     */
    public List getParameters() throws TorqueException
    {
        if (collParameters == null)
        {
            collParameters = getParameters(new Criteria(10));
        }
        return collParameters;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this ParameterDescription has previously
     * been saved, it will retrieve related Parameters from storage.
     * If this ParameterDescription is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getParameters(Criteria criteria) throws TorqueException
    {
        if (collParameters == null)
        {
            if (isNew())
            {
               collParameters = new ArrayList();
            }
            else
            {
                   criteria.add(ParameterPeer.PARAMETER_KEY, getParameterKey() );
                   collParameters = ParameterPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                   criteria.add(ParameterPeer.PARAMETER_KEY, getParameterKey());
                   if (!lastParametersCriteria.equals(criteria))
                {
                    collParameters = ParameterPeer.doSelect(criteria);
                }
            }
        }
        lastParametersCriteria = criteria;

        return collParameters;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getParameters(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getParameters(Connection con) throws TorqueException
    {
        if (collParameters == null)
        {
            collParameters = getParameters(new Criteria(10), con);
        }
        return collParameters;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this ParameterDescription has previously
     * been saved, it will retrieve related Parameters from storage.
     * If this ParameterDescription is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getParameters(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collParameters == null)
        {
            if (isNew())
            {
               collParameters = new ArrayList();
            }
            else
            {
                     criteria.add(ParameterPeer.PARAMETER_KEY, getParameterKey());
                     collParameters = ParameterPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                     criteria.add(ParameterPeer.PARAMETER_KEY, getParameterKey());
                     if (!lastParametersCriteria.equals(criteria))
                 {
                     collParameters = ParameterPeer.doSelect(criteria, con);
                 }
             }
         }
         lastParametersCriteria = criteria;

         return collParameters;
     }

    

     
      
         
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this ParameterDescription is new, it will return
     * an empty collection; or if this ParameterDescription has previously
     * been saved, it will retrieve related Parameters from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in ParameterDescription.
     */
    protected List getParametersJoinParameterDescription(Criteria criteria)
        throws TorqueException
    {
        if (collParameters == null)
        {
            if (isNew())
            {
               collParameters = new ArrayList();
            }
            else
            {
                   criteria.add(ParameterPeer.PARAMETER_KEY, getParameterKey());
                   collParameters = ParameterPeer.doSelectJoinParameterDescription(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(ParameterPeer.PARAMETER_KEY, getParameterKey());
               if (!lastParametersCriteria.equals(criteria))
            {
                collParameters = ParameterPeer.doSelectJoinParameterDescription(criteria);
            }
        }
        lastParametersCriteria = criteria;

        return collParameters;
    }
   
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this ParameterDescription is new, it will return
     * an empty collection; or if this ParameterDescription has previously
     * been saved, it will retrieve related Parameters from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in ParameterDescription.
     */
    protected List getParametersJoinProject(Criteria criteria)
        throws TorqueException
    {
        if (collParameters == null)
        {
            if (isNew())
            {
               collParameters = new ArrayList();
            }
            else
            {
                   criteria.add(ParameterPeer.PARAMETER_KEY, getParameterKey());
                   collParameters = ParameterPeer.doSelectJoinProject(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(ParameterPeer.PARAMETER_KEY, getParameterKey());
               if (!lastParametersCriteria.equals(criteria))
            {
                collParameters = ParameterPeer.doSelectJoinProject(criteria);
            }
        }
        lastParametersCriteria = criteria;

        return collParameters;
    }
     



     
    
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
      if (fieldNames == null)
      {
        fieldNames = new ArrayList();
            fieldNames.add("ParameterKey");
            fieldNames.add("AllowedValues");
            fieldNames.add("DefaultValue");
            fieldNames.add("Description");
            fieldNames = Collections.unmodifiableList(fieldNames);
      }
      return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
            if (name.equals("ParameterKey"))
    {
              return getParameterKey();
          }
            if (name.equals("AllowedValues"))
    {
              return getAllowedValues();
          }
            if (name.equals("DefaultValue"))
    {
              return getDefaultValue();
          }
            if (name.equals("Description"))
    {
              return getDescription();
          }
            return null;
    }
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
            if (name.equals(ParameterDescriptionPeer.PARAMETER_KEY))
        {
              return getParameterKey();
          }
            if (name.equals(ParameterDescriptionPeer.ALLOWED_VALUES))
        {
              return getAllowedValues();
          }
            if (name.equals(ParameterDescriptionPeer.DEFAULT_VALUE))
        {
              return getDefaultValue();
          }
            if (name.equals(ParameterDescriptionPeer.DESCRIPTION))
        {
              return getDescription();
          }
            return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
    {
              return getParameterKey();
          }
            if (pos == 1)
    {
              return getAllowedValues();
          }
            if (pos == 2)
    {
              return getDefaultValue();
          }
            if (pos == 3)
    {
              return getDescription();
          }
                return null;
    }

     


    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
             save(ParameterDescriptionPeer.getMapBuilder()
                .getDatabaseMap().getName());
     }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
         try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }

     }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
      {
        alreadyInSave = true;



  
        // If this object has been modified, then save it to the database.
        if (isModified())
        {
            if (isNew())
            {
                ParameterDescriptionPeer.doInsert((ParameterDescription) this, con);
                setNew(false);
            }
            else
            {
                ParameterDescriptionPeer.doUpdate((ParameterDescription) this, con);
            }
        }

                                    
                
          if (collParameters != null)
          {
              for (int i = 0; i < collParameters.size(); i++)
              {
                  ((Parameter) collParameters.get(i)).save(con);
              }
          }
                  alreadyInSave = false;
      }
      }


                        
    
    

        /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  parameter_key ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
                    setParameterKey(key.toString());
            }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
                    setParameterKey(key);
            }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getParameterKey());
    }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public ParameterDescription copy() throws TorqueException
    {
        return copyInto(new ParameterDescription());
    }

    protected ParameterDescription copyInto(ParameterDescription copyObj) throws TorqueException
    {
        copyObj.setParameterKey(parameter_key);
        copyObj.setAllowedValues(allowed_values);
        copyObj.setDefaultValue(default_value);
        copyObj.setDescription(description);

                      copyObj.setParameterKey((String)null);
                        

                                  
                
        List v = getParameters();
        for (int i = 0; i < v.size(); i++)
        {
            Parameter obj = (Parameter) v.get(i);
            copyObj.addParameter(obj.copy());
        }
              
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public ParameterDescriptionPeer getPeer()
    {
        return peer;
    }
}
