
package de.vahrson.pt.om;


import java.util.List;

import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;


/** 
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Feb 25 10:33:02 CET 2005]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Orf 
    extends de.vahrson.pt.om.BaseOrf
    implements Persistent
{
    /**
     * Answer a list of orf whose usa match the given usa
     * @param usa
     * @return
     */
    public static List listMatchingOrfs(String usa) throws Exception{
        Criteria query= new Criteria();
        query.add(OrfPeer.USA,(Object)("%" + usa + "%"), Criteria.LIKE);
        return OrfPeer.doSelect(query);
    }
}
