package de.vahrson.pt.om;

/** 
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Mar 03 00:16:53 CET 2005]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class ParameterPeer 
    extends de.vahrson.pt.om.BaseParameterPeer
{
}
