package de.vahrson.pt.om;

/** 
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Feb 04 11:59:44 CET 2004]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class PrimerPeer 
    extends de.vahrson.pt.om.BasePrimerPeer
{
}
