
package de.vahrson.pt.om;


import org.apache.torque.om.Persistent;

/** 
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Feb 04 11:59:44 CET 2004]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Primer 
    extends de.vahrson.pt.om.BasePrimer
    implements Persistent
{
	public String toString() {
		return getPrimerId() + "\t" + getSeqlen() + "\t" + getSequence();
	}
	
	public String getSimpleName() {
        return simpleFromLocalName(getLocalName());
	}

	public static String simpleFromLocalName(String localName) {
		String [] fields= localName.split("[:/]+");
        return fields[fields.length-1];
	}

    public static Primer primerFromHit(int hitId) throws Exception{
    	Hit h=HitPeer.retrieveByPK(hitId);
    	return PrimerPeer.retrieveByPK(h.getPrimerId());
    }
}
