
package de.vahrson.pt.om;


import org.apache.torque.om.Persistent;

/** 
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Feb 22 16:23:01 CET 2005]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class ProjectHit 
    extends de.vahrson.pt.om.BaseProjectHit
    implements Persistent
{
}
