package de.vahrson.pt.om.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Thu Mar 17 11:26:19 CET 2005]
  *
  */
public class PrimerMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "de.vahrson.pt.om.map.PrimerMapBuilder";


    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("pt");

        dbMap.addTable("primer");
        TableMap tMap = dbMap.getTable("primer");

                tMap.setPrimaryKeyMethod(TableMap.ID_BROKER);
        
                tMap.setPrimaryKeyMethodInfo(tMap.getName());
        
                                      tMap.addPrimaryKey("primer.PRIMER_ID", new Integer(0));
                                                        tMap.addColumn("primer.LOCAL_NAME", new String());
                                                        tMap.addColumn("primer.SEQUENCE", new String());
                                                        tMap.addColumn("primer.SEQLEN", new Integer(0));
                                                        tMap.addColumn("primer.TM", new Double(0));
                                                        tMap.addColumn("primer.GC", new Double(0));
                                                        tMap.addColumn("primer.STATUS", new Integer(0));
                              }
}
