package de.vahrson.pt.om.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Thu Mar 17 11:26:19 CET 2005]
  *
  */
public class ProjectMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "de.vahrson.pt.om.map.ProjectMapBuilder";


    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("pt");

        dbMap.addTable("project");
        TableMap tMap = dbMap.getTable("project");

                tMap.setPrimaryKeyMethod(TableMap.ID_BROKER);
        
                tMap.setPrimaryKeyMethodInfo(tMap.getName());
        
                                      tMap.addPrimaryKey("project.PROJECT_ID", new Integer(0));
                                                        tMap.addColumn("project.NAME", new String());
                                                        tMap.addColumn("project.SHORTNAME", new String());
                                                        tMap.addColumn("project.DIRECTORY_PATH", new String());
                                                        tMap.addForeignKey(
                "project.PARENT_ID", new Integer(0) , "project" ,
                    "project_id");
                              }
}
